apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gmail-auth
  namespace: monitoring
data:
  password: # Paste base64 encoded value of sender's email address password here.


# We should add this file in gitignore file, as it contains sensitive data (i.e. email password)
